"""create initial tables

Revision ID: 91b2359f3c05
Revises:
Create Date: 2026-07-31 11:16:44.619587

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91b2359f3c05"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "check_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target", sa.String(length=253), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("latency", sa.Float(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('up', 'issues', 'down')", name="ck_check_history_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "check_history_target_time_idx",
        "check_history",
        ["target", "checked_at"],
        unique=False,
    )
    op.create_table(
        "outage_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target", sa.String(length=253), nullable=False),
        sa.Column("reporter_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "outage_reports_rate_limit_idx",
        "outage_reports",
        ["target", "reporter_hash", "created_at"],
        unique=False,
    )
    op.create_index(
        "outage_reports_target_time_idx",
        "outage_reports",
        ["target", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("outage_reports_target_time_idx", table_name="outage_reports")
    op.drop_index("outage_reports_rate_limit_idx", table_name="outage_reports")
    op.drop_table("outage_reports")
    op.drop_index("check_history_target_time_idx", table_name="check_history")
    op.drop_table("check_history")
    # ### end Alembic commands ###
